### ISSUE TITLE
The "scale" dropdown should have the hand cursor (like the "speed" dropdown)

### ISSUE THREAD

**Issue by HP4k1h5** [CSIS-iLab/satellite-dashboard#200]

**Comment by HP4k1h5** [comment]
I'm seeing the hand icon for both scale and speed dropdowns.

**Comment by jnschrag** [comment]
I think this will be resolved if we set `:searchable="false"` on the scale dropdown like it is on the speed dropdown. Searchable dropdowns intentionally are set to have a text cursor over the input, but searching isn't a requirement for this dropdown.

See [speed dropdown](https://github.com/CSIS-iLab/satellite-dashboard/blob/main/components/timeline/Timeline.vue#L11)
See [scale dropdown](https://github.com/CSIS-iLab/satellite-dashboard/blob/main/components/timeline/Timeline.vue#L80)

Happy to submit a PR to do this, but didn't want to do it since you self-assigned this issue.

**Comment by HP4k1h5** [comment]
Close #200
