### ISSUE TITLE
Align the sort button to the right

### ISSUE THREAD

**Issue by HP4k1h5** [CSIS-iLab/satellite-dashboard#219]

**Comment by jnschrag** [comment]
@tuckabelle The button is right aligned. The issue is that the table is actually too wide to fit in that space, so it hangs over a little bit.

<img width="430" alt="Screen Shot 2021-08-10 at 4 09 03 PM" src="https://user-images.githubusercontent.com/1896496/128928233-624de24a-cfff-4531-8fe9-9078eefdfce4.png">

The only options we have are:
1. Increase the width of the whole panel
2. Adjust the padding on the left/right sides of the panel to increase the amount of space for the content
3. Adjust the spacing within the table row. The padding we have between the columns and the amount of content doesn't fit in the space. I think that has to do with the fact that the satellite names are all uppercase and we have situations where there's multiple countries listed.

**Comment by tuckabelle** [comment]
It looks like there's some extra space at the end of the title div
![image](https://user-images.githubusercontent.com/13002217/129039699-77920bb5-6e9c-4b83-ab02-98605f04f9cd.png)


I fiddled by taking away the grid columns and making the max-width of the title div to 128px
![image](https://user-images.githubusercontent.com/13002217/129040768-905f9d44-7f24-459e-88c8-bbe47ca92b7b.png)

![image](https://user-images.githubusercontent.com/13002217/129040755-715e3291-30f3-4cff-a447-fe7b735f7bd7.png)


Does that work or is there something I'm overlooking?

**Comment by jnschrag** [comment]
Thanks for digging into this, @tuckabelle. It is a little bit more complicated than that - this is actually a reusable component used throughout the site, so I can't just get rid of the columns as it'll break things in other places. But I'll see if I can make a variation for just this filter list with the changes you suggested and see if that works.
