### ISSUE TITLE
Component: Object Details - Details

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#45]
A subcomponent/tab of the Object Details Component (#44).

## Details
- [x] Alternative Name(s)
- [x] ID
- [x] Status
- [x] Purpose
- [x] Type
- [x] Country of Jurisdiction
- [x] Operator
- [x] Launch Date
- [x] Country of Launch Site
- [x] Launch Site
- [x] Launch Vehicle
- [x] Contractor
- [x] Lifetime
- [x] NORAD ID

## Orbit
- [x] Updated from:
  - [x] Source Name
  - [x] Source Date
  - [x] Most recent data pull date
- [x] Apogee
- [x] Argument of perigee
- [x] Perigee
- [x] Eccentricity
- [x] Inclination
- [x] Longitude
- [x] Mean motion
- [x] Orbital period
- [x] Orbital speed
- [x] Semi-major axis
- [x] RAAN

### Get current orbit
- [x] Get the current orbit based on the timeline. Right now, all values in this section default to the first orbit that we have for the satellite, but not necessarily the one we want to use for the given time.

## Nearby ITU Filings
Table of ITU filings for the object. [ITU filings](https://docs.google.com/spreadsheets/d/10eGYBNPs1xrD8FHGMrjMDq9_WVKuwlFbS8yAxKTrrtI/edit#gid=0) are looked up by the current longitude.
_Example:_ A satellite with a longitude of -177 should result in 29 filings. A satellite with a longitude -179 (which is missing from the spreadsheet) would look at neighboring frequencies up to +/- 0.5 until it finds a match.

For each frequency, show:
- [x] Longitude
- [x] Country
- [x] Bands
- [x] Link

## Comments
- [x] Any comments associated with the satellite in the CMS

**Comment by HP4k1h5** [comment]
While it used to be possible with Google sheets v3 API to do filter/query queries on the sheet, and bring back a subset of the original rows/cells, v4 has deprecated this feature (see e.g. [gh issue](https://github.com/theoephraim/node-google-spreadsheet/issues/346), [google groups comment](https://groups.google.com/g/google-spreadsheets-api/c/MozmxNCZHpA/m/S6o2UPr8BwAJ) ). Sheets v3 API is being shut down in August, 2021
> Update: The Google Sheets v3 API will be shut down on August 2, 2021. Follow this migration guide to update your applications so that they use the v4 API...

This leaves us with fetching the entire sheet (~1MB) at once and then filtering on the client side. Because our app is already heavy on front-loaded data queries, and keeps a lot of data in memory at all times, it might be preferable to add these values to a sql table and create an API endpoint in WordPress REST API. This would reduce initial load time, reduce data inconsistencies and reduce our overall memory footprint, which is getting big now at 185MB.

**Comment by jnschrag** [comment]
> This leaves us with fetching the entire sheet (~1MB) at once and then filtering on the client side. Because our app is already heavy on front-loaded data queries, and keeps a lot of data in memory at all times, it might be preferable to add these values to a sql table and create an API endpoint in WordPress REST API. This would reduce initial load time, reduce data inconsistencies and reduce our overall memory footprint, which is getting big now at 185MB.

Got it. That makes sense to me. We've definitely already got a behemoth of an app on our hands, so anything we can do to make that better is 👍 with me. Let me know if you want to discuss this, otherwise I'll trust you to work through this solution.

**Comment by HP4k1h5** [comment]
Ok. For now adding ~1MB to ~200MB is not going to break the camel's back, but there might be a few things we can do to get the footprint smaller, and eventually moving this data to sql could be one of those
